{{- if .Values.vaultinjector }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsmx-agent-{{ .Values.name }}-with-injector
  labels:
    agent.opsmx.com/name: {{ .Values.name }}
    agent.opsmx.com/role: agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opsmx-agent-{{ .Values.name }}-with-injector
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: {{ .Values.vaultrole }}
        vault.hashicorp.com/agent-inject-secret-authtoken: {{ .Values.vaultmount }}/data/{{ .Values.vaultpath }}/authtoken
        vault.hashicorp.com/secret-volume-path-authtoken: '/app/secrets'
        vault.hashicorp.com/agent-inject-template-authtoken: |
            {{ "{{" }}- with secret "{{ .Values.vaultmount }}/data/{{ .Values.vaultpath }}/authtoken" -{{ "}}" }}
            {{ "{{" }} .Data.data.authtoken {{ "}}" }}
            {{ "{{" }}- end -{{ "}}" }}
        vault.hashicorp.com/agent-inject-secret-services.yaml: {{ .Values.vaultmount }}/data/argocd-tcb/services.yaml
        vault.hashicorp.com/secret-volume-path-services.yaml: '/app/config'
        vault.hashicorp.com/agent-inject-template-services.yaml: |
            {{ "{{" }}- with secret "{{ .Values.vaultmount }}/data/{{ .Values.vaultpath }}/services.yaml" -{{ "}}" }}
            {{ "{{" }} .Data.data.services {{ "}}" }}
            {{ "{{" }}- end -{{ "}}" }}
      labels:
        app: opsmx-agent-{{ .Values.name }}-with-injector
        agent.opsmx.com/name: {{ .Values.name }}
        agent.opsmx.com/role: agent
    spec:
      serviceAccountName: opsmx-agent-{{ .Values.name }}
      containers:
      - name: opsmx-agent-{{ .Values.name }}
        image: quay.io/opsmxpublic/agent-client:v4.2.3
        volumeMounts:
        - name: config
          mountPath: /app/config/config.yaml
          subPath: config.yaml
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      volumes:
      - name: config
        configMap:
          name: opsmx-agent-{{ .Values.name }}
          items:
          - key: "configFile"
            path: "config.yaml"
{{- end -}}
