apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: opsmx-agent-{{ .Values.name }}-auth
  labels:
    agent.opsmx.com/name: {{ .Values.name }}
    agent.opsmx.com/role: agent
data:
  authtoken: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJbXRwWkNJNkltRjFkR2gwYjJ0bGJpSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBZWFFpT2pFM01ESXhNakV3T1Rnc0ltbHpjeUk2SW05d2MyMTRMV0ZuWlc1MExXRjFkR2dpTENKdmNITnRlQzVoWjJWdWRDNXVZVzFsSWpvaWRHTmlNU0o5LnhPRUJuelY0UWE5V21GaDM5VThhRTRLYWVtd2FFNFR1dnl4VmdHTUhzRzA=