{{- if not .Values.vaultinjector }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: opsmx-agent-{{ .Values.name }}-auth
spec:
  type: kv-v2

  # mount path
  mount: {{ .Values.vaultmount }}

  # path of the secret
  path: {{ .Values.vaultpath }}/authtoken

  # dest k8s secret
  destination:
    name: opsmx-agent-{{ .Values.name }}-auth
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: {{ .Values.vaultauth }}
{{- end }}
