apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: carina-instance
  name: carina-instance
spec:
  ports:
  - name: carina-instance
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: oes
    component: carina-instance
  type: ClusterIP
