apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oes
    component: carina-instance
  name: carina-instance
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.carinaReplicaCount }}
  selector:
    matchLabels:
      app: oes
      component: carina-instance
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oes
        component: carina-instance
    spec:
      containers:
      - image: quay.io/opsmxpublic/carina-instance:v1.13.1
        imagePullPolicy: IfNotPresent
        name: carina-instance
        ports:
        - containerPort: 8090
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: argocd-server
      serviceAccountName: argocd-server
      terminationGracePeriodSeconds: 30