apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opsmx-agent-{{ .Values.name }}
  labels:
    agent.opsmx.com/name: {{ .Values.name }}
    agent.opsmx.com/role: agent
subjects:
- kind: ServiceAccount
  name: opsmx-agent-{{ .Values.name }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: opsmx-agent-{{ .Values.name }}
  apiGroup: rbac.authorization.k8s.io