apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opsmx-binding-{{ .Values.name }}
  labels:
    agent.opsmx.com/name: {{ .Values.name }}
    agent.opsmx.com/role: agent
subjects:
- kind: ServiceAccount
  name: opsmx-agent-{{ .Values.name }}
roleRef:
  kind: Role
  name: opsmx-role-{{ .Values.name }}
  apiGroup: rbac.authorization.k8s.io